// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcbe_sAFvMEpTuzbtsn2ZkG4PljT2RIGw',
    appId: '1:1055566752136:web:1003c88e23baff2d40323d',
    messagingSenderId: '1055566752136',
    projectId: 'wtwinds',
    authDomain: 'wtwinds.firebaseapp.com',
    storageBucket: 'wtwinds.firebasestorage.app',
    measurementId: 'G-GH4T39VPCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxwUrbi7LPHuzA7zWCjT75pfqcOQvzIA',
    appId: '1:1055566752136:android:dfb13fc8d09082bc40323d',
    messagingSenderId: '1055566752136',
    projectId: 'wtwinds',
    storageBucket: 'wtwinds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGUwZTzxAs053rjKa8H4wCK-AE9wwiAh0',
    appId: '1:1055566752136:ios:ae8549da45b2c82a40323d',
    messagingSenderId: '1055566752136',
    projectId: 'wtwinds',
    storageBucket: 'wtwinds.firebasestorage.app',
    androidClientId: '1055566752136-n4sehctqmriaicoujprq7t412qjf82mr.apps.googleusercontent.com',
    iosClientId: '1055566752136-cf77qio8l0a6f7f15u4e9oskf63p04qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.wtwindsNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGUwZTzxAs053rjKa8H4wCK-AE9wwiAh0',
    appId: '1:1055566752136:ios:ae8549da45b2c82a40323d',
    messagingSenderId: '1055566752136',
    projectId: 'wtwinds',
    storageBucket: 'wtwinds.firebasestorage.app',
    androidClientId: '1055566752136-n4sehctqmriaicoujprq7t412qjf82mr.apps.googleusercontent.com',
    iosClientId: '1055566752136-cf77qio8l0a6f7f15u4e9oskf63p04qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.wtwindsNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcbe_sAFvMEpTuzbtsn2ZkG4PljT2RIGw',
    appId: '1:1055566752136:web:033a2040542d7bfd40323d',
    messagingSenderId: '1055566752136',
    projectId: 'wtwinds',
    authDomain: 'wtwinds.firebaseapp.com',
    storageBucket: 'wtwinds.firebasestorage.app',
    measurementId: 'G-66FL1S3N48',
  );

}